version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$ECR_URI"
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:=latest}
      - SHORT_TAG=$(echo "$IMAGE_TAG" | cut -c1-12)
      - IMAGE_URI="$ECR_URI:$SHORT_TAG"
      - echo "IMAGE_URI=$IMAGE_URI"
  build:
    commands:
      - echo "Build Docker image..."
      - docker build -t "$IMAGE_URI" .
  post_build:
    commands:
      - echo "Push Docker image..."
      - docker push "$IMAGE_URI"
      - printf '%s' "$IMAGE_URI" > image-uri.txt
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - docker-compose.prod.yml
    - image-uri.txt
